### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by tombishop1** [tombishop1/itraxR#1]
Can you give an example input that works? My best guess so far is to load everything into a dataframe `df` by running my script (`source("itrax.R`), followed by the input `r` for filename, and `0` for drilling depth. Then, running the averaging script (`source("basicmean.r")`), with the input `basicmean("df", 0, 5, 20)` returns the output:

`Standard deviation NA` 
`Mean NA `
`Warning message:`
`In mean.default(data_in_range) :`
 ` argument is not numeric or logical: returning NA`

I get a similar error when I run `mean(df[5:10, ])`, but not when I run `mean(df[5:10, "Cr"])`, which returns `[1] 1.891667`.

**Comment by gcapes** [comment]
If you load the data you sent me using your script (pick any value for drilling depth), then run these commands after sourcing the basicmean.r file, you should get the output shown.
```
> source('<path-on-your-machine-to-this-repo>/basicmean.r')
> basicmean(df$Ca,df$position,85,86)
```
Standard deviation 2.098576 
Mean 11.6026 

It's _very_ work-in-progress at the moment!

**Comment by tombishop1** [comment]
Got it, thanks.
