### ISSUE TITLE
Turn the itrax.R Script into a Function

### ISSUE THREAD

**Issue by tombishop1** [tombishop1/itraxR#3]
I realise my itrax.R script is a bit goofy and it would be better if I were to turn the individual functionality into separate functions that can be loaded, in the same way you implemented 'basicmean()'. Perhaps:

- `itraximport()`, that deals with lines 1 to 51,
- `itraxbinning()`, that deals with lines 52 to 59, and
- `itraxordination()`, that deals with the (as yet unwritten) 60 to 64.

This would make it more modular, flexible and customisable. It's probably better to knock my goofy "command prompt" format on the head earlier rather than later in this project.

**Comment by gcapes** [comment]
I agree - best to write the functions to do the work, then if you want a GUI, write that at the end.

**Comment by tombishop1** [comment]
This was finished in 7ad5d6a, and the old script removed.
